### ISSUE TITLE
MathJax fonts?

### ISSUE THREAD

**Issue by imjeffp** [adamsilverstein/mathml-block#14]
This is probably a MathJax issue, and I know you can't diagnose much from a screen shot, but any thoughts on the font issue here?
![Screen Shot 2019-07-23 at 1 06 39 PM](https://user-images.githubusercontent.com/25798597/61736126-ffa99600-ad4a-11e9-8716-8dbee6aab40b.png)

**Comment by imjeffp** [comment]
After much perusal of the MathJax documentation, I think the answer is here: http://docs.mathjax.org/en/latest/options/output-processors/HTML-CSS.html#configure-html-css

![Screen Shot 2019-07-23 at 3 22 11 PM](https://user-images.githubusercontent.com/25798597/61744787-bca4ee00-ad5d-11e9-9be2-e6c59ea3df10.png)

I think I want 
`MathJax.Hub.Config({
  "HTML-CSS": {
    fonts: ["STIX", "TeX"]
  }
});`

If I'm reading that right, I should almost always get Stix, which is designed to pair with Times, which would make me happy.

So my question now is, "Where do I add this bit of code?"

**Comment by imjeffp** [comment]
The more I read, the less I know. Mathml-block uses `config=TeX-MML-AM_CHTML`. According to a post [here](https://groups.google.com/forum/#!searchin/mathjax-users/STIX%7Csort:date/mathjax-users/Mm_pw4_cZgA/8aUZus3WBAAJ), "CommonHTML currently only supports the MathJax TeX fonts (not the STIX fonts or any of the other web-based fonts available in HTML-CSS)."

So it seems that I'm going to have to be happy with the v's looking like u's. I'll get over it.

**Comment by adamsilverstein** [comment]
Hey @imjeffp thanks for the issue! It is possible this is an issue with the plugin - can you give the MathJax demo a test with your formula to see how it renders there? https://www.mathjax.org/#demo

**Comment by adamsilverstein** [comment]
Also possibly related, I'm going to try switching to loading the fonts from the CDN vs bundling them with the plugin.

**Comment by adamsilverstein** [comment]
Hey @imjeffp - in the latest release I load the MathJax script from the CDN which should include all fonts. I also added a filter you can use to alter the config string passed to the script. Can you give it a try?

**Comment by adamsilverstein** [comment]
Closing as resolved/inactive.
