### ISSUE TITLE
Add support for AMP

### ISSUE THREAD

**Issue by westonruter** [adamsilverstein/mathml-block#5]
It would be nice if the block would output an `amp-mathml` element when `is_amp_endpoint`. This could be done via a "conditionally-dynamic" block, for example at the `template_redirect` action it could check if `is_amp_endpoint()` and if so, then register a `mathml/mathmlblock` block in PHP with a `render_callback` that takes the static markup saved in the editor and convert it to `amp-mathml`. (Idea comes from conversation with @youknowriad.)

In the same way, `potentially_add_front_end_mathjax_script()` could short-circuit when `is_amp_endpoint()`.

**Comment by adamsilverstein** [comment]
👍 thanks for the suggestion
