### ISSUE TITLE
plugin name

### ISSUE THREAD

**Issue by pkra** [adamsilverstein/mathml-block#9]
This is perhaps a random question but I've been wondering about this ever since amp-mathml.

This plugin is called "mathml block" but neither requires MathML on the input side nor does it create MathML on the output side; it is more a "mathjax block". Why did you put mathml in the name?

**Comment by adamsilverstein** [comment]
@pkra Good question!

MathJax is an implementation detail - in theory we could swap this out for a different library and the plugin would continue to support your formulas.

Regarding  amp-mathml - originally when working on amp-mathml, I was trying to solve for a specific application that used MathML, and was already using MathJax. I wasn't really thinking about the other formats supported by MathJax (LaTeX and AsciiMath notation). I agree the naming here could be better, indicating support for everything - maybe just 'Math Block' and `amp-math`? 

Unfortunately your feedback probably comes a little too late to change things, I feel we may be stuck with the naming.
